#:schema node_modules/wrangler/config-schema.json
name = "luminux-studio"
pages_build_output_dir = ".svelte-kit/cloudflare"

compatibility_date = "2026-04-24"
compatibility_flags = [ "nodejs_compat" ]